version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
  create-infrastructure:  
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout # check out the code in the project directory
        - run: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1
  
  configure_infrastructure:
      docker:
          - image: python:3.7-alpine3.11 
        steps:
          - checkout
          - add_ssh_keys:
                  # You can get this ID in the section where you registered the SSH Key
                  fingerprints: ["70:c2:5f:7b:31:56:83:fc:66:cf:16:54:3b:22:2f:30"] 
          - run:
              name: Install Ansible
              command: |
                  apk add --update ansible
          - run:
              name: Run Playbook and Configure server
              command: |
                  ansible-playbook -i inventory.txt main-remote.yml

workflows:
  
  myWorkflow:
    jobs:
      #- create-infrastructure
      - configure-infrastructure